# 订阅源
rssList:
  - https://example.com/rss
# RSS 请求并发限制
rssLimit: 1
# 上传并发限制
uploadLimit: 1
# 上传失败重试次数
uploadRetry: 3
# 下载并发限制
downloadLimit: 1
# 数据保存地址
dataPath: ./data

# CookieCloud 地址，详见 https://github.com/easychen/CookieCloud
# 也可以使用 cookie-cloudflare，提供兼容 API，详见 https://github.com/CaoMeiYouRen/cookie-cloudflare
cookieCloudUrl: "https://cookiecloud.example.com/get/ABCDEF"
# CookieCloud 加密密码
cookieCloudPassword: ""
# 百度网盘 bduss
bduss: ""
# 百度网盘 stoken
stoken: ""
# 上传到的路径
uploadPath: "/videos"

# 定时执行。如果留空，则立即执行一次，否则定时执行
cronTime: ""

# 自动删除已经上传的文件
autoRemove: false
# push-all-in-one 推送配置，参考 https://github.com/CaoMeiYouRen/push-all-in-one
pushConfigs: []
